ajout page contact
WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P3-GeoCode pull request #13
Opened 2024-06-19 13:22 UTC by Dinetch2023

Ajout du formulaire de contact avec champs et gestion de soumission

Ajout du composant Contact pour permettre aux utilisateurs de soumettre leurs coordonnées et messages. Ajout de champs de saisie pour le nom, l'email, le motif de contact et le message. Implémentation de la gestion de l'état avec le hook useState de React pour la gestion des données du formulaire. Mise en place de la validation du formulaire et de la logique de soumission avec les gestionnaires d'événements handleChange et handleSubmit. Stylisation du formulaire avec Contact.scss pour une cohérence visuelle dans l'application.

Changements effectués :
- Ajout des champs de saisie pour le nom, l'email, le motif et le message.
- Implémentation de la gestion de l'état pour les données du formulaire.
- Ajout de la logique de soumission du formulaire avec console log.
- Ajout du lien vers le centre d'aide avec le composant Link de React Router.

2024-06-19 13:28 UTC, VncPsq approved these changes
Ok pour moi bizarre le changement du package-lock.json

2024-06-19 14:20 UTC, VncPsq requested changes
need to install React lefleat

2024-06-20 12:42 UTC, VncPsq approved these changes
Done Scss, no dead code

2024-06-20 12:43 UTC, fanny-pretre approved these changes
Ok pour moi, structure de contact et du scss uniquement :)

2024-06-20 12:47 UTC, merged